### ISSUE TITLE
DCCS 2.0 - Adaptive Recent Signers Rule

### ISSUE THREAD

**Issue by Zergity** [nextyio/gonex#136]
## Problem
Currently recent signer logic prevents the last n/2 signers to sign again. This effectively enforces the n/2+1 rule for the DCCS/Clique consensus, which allows the network to progress only when at least n/2+1 of the registered signers are active. The main reasons are to prevent the network to be forked and long-range double-spend attack by a small group of signers.

This rule has a critical problem for open public blockchain, for both DCCS/Clique or any stake-based consensus. A large number of registered signers being inactive could harm the network and even hang the network forever, and only a hard fork could resolve it.

PoW-based consensuses have adaptive difficulty, which allows the network to adapt to gradually change of hash power. Gradually, not disrupted.

Stake-based consensuses like DCCS should also be able to adapt to the activeness of its signers. That means active signers can be increased or decreased gradually, without hanging the network altogether.

## Proposal
I propose the **Adaptive Recent Signer** Rule with the following properties.
+ With N is the number of current registered Signers.
+ With M is the number of the unique signers of the last N+N/2 block.
+ A signer is in the recent list if it already signed one of the last M/2 blocks.

## To Be Discussed
At checkpoint where the signer list is updated and the recent list is cleared, there is no way to predict how many of the newly registered signers will be active. If we enforce the n/2+1 rule to N (registered signers list), it could potentially hang the network at the checkpoint when a lot of signers are inactive. If we loosen the rule by not checking the recent signers (like Clique does) in the first N blocks of an epoch, fork and long-range attack can easily be created at the checkpoint. It's the choice between security and liveness for the network.

## Attack Vectors
The **Adaptive Recent Signers** rule is designed to increase the liveness of the DCCS network yet also keep it safe from many types of chain re-org attacks.

**Comment by hadv** [comment]
Doing this way, we can somehow reduce the chance of hangout network but it still might happen when brunch of sealers suddenly go offline at the same time.

**Comment by Zergity** [comment]
> Doing this way, we can somehow reduce the chance of hangout network but it still might happen when brunch of sealers suddenly go offline at the same time.

Exactly. Because that behavior is essential to prevent the network fork. No other consensus can cope with that disruptive change in the network power, not even PoW.

**Comment by Zergity** [comment]
Need more discussion and currently has low priority. Keep a working implementation of the rule in here for future reference: https://github.com/nextyio/gonex/tree/pof-adaptive-recent

**Comment by Zergity** [comment]
This issue can be rejuvenated with #238. #238 allows sealer to join and leave dynamically, without checkpoint nor epoch. Now we need a mechanism to actively kick an inactive sealer out, to keep the consensus adapting with changing signers.

Eth 2.0 has a separated beacon chain for timestamping and slashing inactive validators in shards. Dccs needs some timing condition to forcefully kick inactive sealer out.

**Comment by Zergity** [comment]
> Dccs needs some timing condition to forcefully kick inactive sealer out.

VDF can be a good solution, in the case of network is being stuck (because > n/2 sealer suddenly went offline.) A block with a valid VDF output/proof can still be sealed, and the rest of the sealer (< n/2+1) can seal on top of it.
