### ISSUE TITLE
Consensus contract deployment receipt and logs

### ISSUE THREAD

**Issue by Zergity** [nextyio/gonex#186]
Contracts deployed by consensus only has the code and storage stage. No receipt is recorded in the block.

**Comment by hadv** [comment]
This make any problem @Zergity ? or we need it for block explorer?

**Comment by Zergity** [comment]
> This make any problem @Zergity ? or we need it for block explorer?

Explorer is the first case. We will deploy more consensus contract this way, so it's better to have it. Not nessesary, tho.

**Comment by Zergity** [comment]
Consensus contract deployment is infrequent case. Block initialization transactions and receipts(logs) are implemented with commit 9cb6ab0662c8075fa84e19a0f5dd5ae2d3906103
