### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dapprocket** [nextyio/gonex#218]
#### System information

Gonex version: gonex/v2.0.0-stable
OS & Version: Ubuntu 18.04

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xa95f5e]

goroutine 316 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc42009f040, 0xc42b9f5860, 0xc42ce6e480, 0x0, 0x0, 0xc42d8dba18)
        /mnt/c/Projects/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:825 +0x17de
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc42009f040, 0xc42b9f5860, 0x31c4ab0e56ba5a7a, 0x888a1425cdf7e209, 0xb075f146c1027c3a, 0x94dfad3ae7ced5a5, 0xc42c14f1c0, 0x0, 0x0)
        /mnt/c/Projects/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:437 +0x38d
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc42009f040, 0xc42cc890c0, 0x10, 0x31c4ab0e56ba5a7a, 0x888a1425cdf7e209, 0xb075f146c1027c3a, 0x94dfad3ae7ced5a5, 0xc42c14f1c0, 0x0, 0x0, ...)
        /mnt/c/Projects/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:406 +0x38b
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc42009f040, 0xc42cc890c0, 0x10, 0x31c4ab0e56ba5a7a, 0x888a1425cdf7e209, 0xb075f146c1027c3a, 0x94dfad3ae7ced5a5, 0xc42c14f1c0, 0x0, 0x4a90bda376d5dad6, ...)
        /mnt/c/Projects/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:324 +0x97
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).synchronise(0xc42c9a6ea0, 0xc4200a9740)
        /mnt/c/Projects/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:210 +0x4c8
created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).handleMsg
        /mnt/c/Projects/gonex/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:695 +0xd06

#### Steps to reproduce the behaviour
I ran this node with parameter: --config=gonex.toml, have not tried to run again in other node with similar behavior. Will report later if it is still persist with other node in same parameter config

**Comment by dapprocket** [comment]
[kynex.log](https://github.com/nextyio/gonex/files/3264251/kynex.log)
[kynex-verbosity.log](https://github.com/nextyio/gonex/files/3264252/kynex-verbosity.log)

Please see log files attached

**Comment by hadv** [comment]
it's `out of memory` or crash one time then your service automatically restart with wrong state db. you must to clean all old db to sync again and make sure that your node have at least 4G RAM

```
WARN [06-07|02:54:16.143] Head state missing, repairing chain      number=15460387 hash=40021e…b3c5ca
```

**Comment by Zergity** [comment]
enable swap also stabilize the node and prevent this issue
