### ISSUE TITLE
If we check like this then when user choose 3 (without Endurio) but when exporting the genesis file, it will enable Endurio hardfork at block `0`

### ISSUE THREAD

**Issue by hadv** [nextyio/gonex#224]
If we check like this then when user choose 3 (without Endurio) but when exporting the genesis file, it will enable Endurio hardfork at block `0`

_Originally posted by @hadv in https://github.com/nextyio/gonex/pull/197/files_

**Comment by Zergity** [comment]
https://github.com/nextyio/gonex/commit/10fa9cdcbe9104cdb724e6cf4c34f59892cb4606
