### ISSUE TITLE
nit: the function name sounds a bit confuse. It's difficult to understand what is the `copy contract to address` mean. We may need to choose a better name

### ISSUE THREAD

**Issue by hadv** [nextyio/gonex#225]
nit: the function name sounds a bit confuse. It's difficult to understand what is the `copy contract to address` mean. We may need to choose a better name

_Originally posted by @hadv in https://github.com/nextyio/gonex/pull/197

**Comment by Zergity** [comment]
What it does exactly is "copy a contract (code and stage) to an address in the statedb". Do you have any suggestion for a better name?
