### ISSUE TITLE
we might need to check some edge cases here. When `targetSupply` equals to `lastSupply` then panic error happen  `division by zero`

### ISSUE THREAD

**Issue by hadv** [nextyio/gonex#226]
we might need to check some edge cases here. When `targetSupply` equals to `lastSupply` then panic error happen  `division by zero`

_Originally posted by @hadv in https://github.com/nextyio/gonex/pull/197_

**Comment by Zergity** [comment]
This is no longer apply to the new implementation of the stablecoin.
