### ISSUE TITLE
why change it to `HeaderReader`, It may cause error if caller pass the HeaderReader

### ISSUE THREAD

**Issue by hadv** [nextyio/gonex#229]
why change it to `HeaderReader`, It may cause error if caller pass the HeaderReader  here, due to it cannot be cast to ChainContext in line https://github.com/nextyio/gonex/pull/197/files#diff-0df49c07b1de00da67c908a52c54ea40R50

_Originally posted by @hadv in https://github.com/nextyio/gonex/pull/197_

https://github.com/nextyio/gonex/pull/197#discussion_r287269792

**Comment by Zergity** [comment]
It's needed. But it still need some refining.
