### ISSUE TITLE
Dead number for syncing: 993

### ISSUE THREAD

**Issue by dapprocket** [nextyio/gonex#230]
Many nodes stopped syncing (from beginning with full sync) at block number ending 993:

#19,247,993
#19,049,993
#18,392,993
#15,458,993
#15,431,993

**Comment by dapprocket** [comment]
#15,362,993

**Comment by dapprocket** [comment]
#15,428,993
#15,377,993
#15,539,993

**Comment by hadv** [comment]
amazing number :)

**Comment by hadv** [comment]
@dapprocket please provide server error log. Without that we can't help find the problem.

**Comment by Zergity** [comment]
One of the solution to prevent archiving snapshot state is to use the Clique-style snapshot, which will saved to disk.

**Comment by Zergity** [comment]
(Epoch - CanonicalDepth) block is currently bottleneck because of the trie commiting. Adding mem-swap on node server make the node stablized again.
