### ISSUE TITLE
Missing trie-node after absorbing for a while

### ISSUE THREAD

**Issue by Zergity** [nextyio/gonex#232]
[gonex.log.gz](https://github.com/nextyio/gonex/files/3324781/gonex.log.gz)
[gonex2.log.gz](https://github.com/nextyio/gonex/files/3324864/gonex2.log.gz)
![image](https://user-images.githubusercontent.com/37166829/60091221-4c12ad80-976e-11e9-9ee3-0c3f26e458a2.png)

**Comment by hadv** [comment]
might be duplicated with #220

**Comment by hadv** [comment]
#220 include this bug. due to we already closed it then let work on this issue

**Comment by Zergity** [comment]
They are actually 2 different problem, so new issue makes more sense.
