### ISSUE TITLE
DCCS 2.0 - Sealer Consensus

### ISSUE THREAD

**Issue by Zergity** [nextyio/gonex#238]
## Problems with 1.0
1. Epoch in PoA is used for voting round, in DCCS it serves no purpose yet creating alot of limitation, including joining and leaving requries extremely long time to take effect.
2. Header validation is depend on the state data, preventing the fastsync and lightnodes to properly verify the header chain.

Sealer Random Selection and Voting Mechanism will be discussed in another issues, as they address another aspects of the consensus. #239 #240 

## Proposal for 2.0
1. Sealers request to join and leave the consensus using Gorvernance.RequestToJoin/Leave methods, these tx will put callers to JoinQueue/LeaveQueue.
2. Current active sealers fetch all queueing requests, recorded them to block header, and set their state to JoinPending/LeavePending.
Note: This action can happens anytime a sealer is willing to do. There's no consensus rule when the queued request must be processed. It's all up to the current sealers will. This can be specified by a mining node param. Sealers can ignore this action altogether, if all the current sealers reject to do this, no change in sealer list will be made.
3. There're 2 levels of header verification for step 2:
a. State verification (full node): the new joining/leaving requests can be verified by the contract and consensus code. If the request is invalid, it would be invalidated by the consensus, and the block is never accepted by the current active sealers.
b. Header-only verification (light/fast node): the new joining/leaving requests recorded in the block header is only checked for the data format, the actual condition of each request is not verified here because the lack of state data. These requests will be verified by 256 valid signed blocks after this. If the data is falsely forged, the attacker must control all sealers of the next 256 blocks.
4. 256 block after the joining/leaving request is recorded into the header, the request will take effect. The requested sealers will be included in (or excluded from) the Active Sealers from this block (requested block + 256).

The pending 256 blocks can be configured by the consensus. 256 is a good choice because is the max headers cached by the gonex client.

## Results
1. Epoch can be removed.
2. Fast-sync and light client can be secured without any state data.
3. Joining and leaving the consensus only need to wait for a relatively small constant time.

## Alternatives
Another approach to verify the header chain, is including Merkle Proof of the required state for each requested sealer in the header. Fast-sync and lightclient can verify the valid request in the header imediately using the Merkle Proof. This is quite complex for lightclient, and put heavier load in the header chain, which is maintained by the whole network.

**Comment by hadv** [comment]
> Note: This action can happens anytime a sealer is willing to do. There's no consensus rule when the queued request must be processed. It's all up to the current sealers will. This can be specified by a mining node param. Sealers can ignore this action altogether, if all the current sealers reject to do this, no change in sealer list will be made.

We may do in a deterministic way. When there's item on queue then sealer must be cast the first item in the queue to new block header that sealer prepare to seal

**Comment by Zergity** [comment]
We shouldn't enforce anything unless it's nessesary. Is there any reason to enforce this?

**Comment by hadv** [comment]
> We shouldn't enforce anything unless it's necessary. Is there any reason to enforce this?

enforce to apply request join/leave consistently; or at least by default, we need to choose a way to cast pending queue; otherwise, sealer will code them self?

**Comment by Zergity** [comment]
Defaut implemetation will include the request imediately in the next block it's confirmed. But it doesn't need to be enforced.

**Comment by Zergity** [comment]
The only rule we need to enforce is: at the block it's included in the header, the sealer must be in the Queue, which means, it has enough stake to join the queue.

**Comment by hadv** [comment]
> The only rule we need to enforce is: at the block it's included in the header, the sealer must be in the Queue, which means, it has enough stake to join the queue.

That's why I concern about the Prepare() function, it will be called only when mining then it will be fine. 

But it seems that when running fast-sync without mining, node still call Prepare(). Need to re-check for sure!

**Comment by Zergity** [comment]
@hadv addressing the re-ordering checkpoint and recently, one solution is to re-ordering only one sealer position at a time, so the recent rule can still apply. Overtime, the list will be fully shuffled, but not too disrupting to break the consensus recent rule.

This strategy is much aligned with the gradually change of sealer list provides by this proposal.

**Comment by hadv** [comment]
> one solution is to re-ordering only one sealer position at a time

dont know what you mean here!

**Comment by Zergity** [comment]
> > one solution is to re-ordering only one sealer position at a time
> 
> dont know what you mean here!
Could be like this, 1 sealer at a time. With some selecting condition, it works seamlessly without ever clearing the recent list.
Before:
**A** B C D E F
After:
B C D E **A** F
