### ISSUE TITLE
Update chain config for ThangLong HF on mainnet

### ISSUE THREAD

**Issue by hadv** [nextyio/gonex#66]
When we can decide the hardfork block number and nexty governance smart contract address then we can update the default chain config for client to ready for the hardfork

ThangLongBlock = `15,360,000`
ThangLongEpoch = `3000`
Contract = `0x12345`
StakeRequire = `50,000 NTF`
StakeLockHeight = `30,000`

**Comment by hadv** [comment]
need to update `ThangLongBlock` to **15,360,000**

**Comment by Zergity** [comment]
https://github.com/nextyio/gonex/commit/3761fe97f5d3018a60e1d92e991488ba40fc8fbc
