### ISSUE TITLE
historical state pruning

### ISSUE THREAD

**Issue by hadv** [nextyio/gonex#94]
https://github.com/ethereum/go-ethereum/pull/18418

> # I'm still writing this, just ignore for now
> **This is a work in progress. Some features are broken (sync serving, fast sync, clique gc) and it's not backwards compatible (i.e. needs a resync). This PR exists mostly to facilitate discussions.**
> 
> ## Background
> In Ethereum, the state is stored in a number of Merkle-Patricia tries. Each block defines the root hash of the account trie, which maps hashes to the current status of every account within the network: a data quadruple consisting of `balance`, `nonce`, `codehash`, `roothash`:
> 
> * The balance and nonce are plain data fields.
> * The code hash is an external reference to a EVM bytecode.
> * The root hash is an external reference to a storage Merkle-Patricia trie, which is similar to the account trie, except the stored data blobs are 32 byte words, not account data-quadruples.
> 
> At every block, a subset of these accounts change via mining, transfers and EVM code execution; whilst at the same time new accounts may be created and old ones destroyed (self-destruct or state clearing). Since we don't care about past state, there's no need to store the old data on disk any more, we could theoretically just delete it.
> 
> In practice, however, there are a lot of limitations which make deleting past data complicated:
> 
> * The state of Ethereum mainnet currently takes up about 7-8GB. It is infeasible to store the entire state for every single block independently (we're at block 7M, so using an arithmetic progression from 0 bytes at block 0 to 7GB at block 7M, storing every block's data would total to 24.5 PB). Since only a tiny part of the state changes across subsequent blocks, Ethereum nodes store data only once, and simply refer to them via hash from multiple tries instead of duplicating. This reduces the full storage requirement to around 1.8TB, but the cost is that **we don't know how many tries refer to the same data**.
> * The Ethereum networking protocol (`eth/63`) has a data retrieval mechanism where a remote node can request a trie node to be returned based it's hash. This permits nodes to cryptographically provably fast sync, by gradually expanding the state trie starting from its root, cascading down to the leaves and to the storage tries. This also means that **nodes cannot change their storage model without breaking the wire protocol.**
> 
> ## Lessons from the past
> It's not the first time we've investigated implementing historical state pruning. Actually, I myself implemented [4 different versions](https://github.com/ethereum/go-ethereum/pull/2111) of pruning and Jeff [one more](https://github.com/ethereum/go-ethereum/pull/2489), all of which got discarded eventually as unworkable.
> 
> I won't reiterate the past attempts here, just the most important lessons we've learnt from them:
> 
> * There's no meaningful way to store a Merkle-Patricia tree on disk, since it needs to be hash-indexed (keys are random by definition). Any data that hits the disk incurs a significant insertion cost and if we want to delete it afterwards, a huge removal cost (removals entail expensive trie traversals). This is relevant for every hash-indexed metadata too. **Any solution that avoids writing something to disk will perform orders of magnitude better than the equivalent that writes and eventually deletes!**
> * The Ethereum state growth is currently unbounded. It's somewhat kept under control by the block gas limit, but still asymptotically tends towards infinity. This mean that iterating the entire state for whatever reason will take more and more time as the chain progresses (last we've measured it takes 5-20? minutes on a fast SSD). **Any solution that depends on on iterating the state will die in the short-term, as there will exist a critical point when the operation takes more than the idle period!**
> 
> ## In-memory garbage collection
> The first working (alas partial) solution to the problem was introduced by Geth 1.8.0 (and tuned throughout the 1.8.x release family) was garbage collection based on in-memory reference counting.
> 
> The base idea is simple: instead of storing every trie node as a `hash -> value` mapping, also store the number of external tries that refer to the same data: `hash -> {value, refcount}`. Whenever a new trie references something that already exists, we bump the existing node's counter. When an old trie is to be deleted, dereference its root, decrementing the refcounts of all children. If a child counter reaches 0, it can also be dereferenced, cascading downwards.
> 
> The complexity is in the practicalities: on mainnet every block modifies a few thousand trie nodes, which result in a few tens of thousands of refcount changes. Pushing those updates into the database instantly murders performance (along with your SSD), keeping them all in memory murders your RAM (especially during the Shanghai DoS attaks).
> 
> Geth 1.8.x's garbage collector works by introducing a new write cache above the disk database. Whenever a trie attempts to write data to disk, the write is hijacked by this intermediate layer, which annotates the data with a reference counter and retains it in memory. Tries can freely increment and decrement the counters for anything still in-memory, thus also prune any node that was deprecated quickly enough. If a node hit disk, it's not reference counted any more and cannot be pruned.
> 
> This mechanism works nicely because the reference counting overhead is only in-memory, so it's fast; and permitting nodes to be flushed to disk while maintaining correctness allows gracefully handling the scenarios where everything doesn't fit into memory. The more memory the cache is permitted, the less often it needs to push data to disk, so the more junk it can prune away
> 
> Unfortunately, even with "infinite" cache allowance, some data **must** be pushed to disk when restarting Geth (or periodically to avoid a full re-sync after a crash). The in-memory garbage collector in incapable of pruning this data away, so this still adds up.
> 
> This mechanism can bring down the data requirement of a full node (doing a full sync) from 1.8TB to a mere 320GB (with a 2GB cache allowance), pruning away approximately 90% of historical junk (~100GB is the chain, which cannot be pruned). A fast sync however only needs 135GB, which means there's still 185GB worth of junk that we could remove in the ideal case (numbers are approximate).
> 
> ## Disk-based garbage collection

**Comment by Zergity** [comment]
Solved by the db freezer funtionality of geth 1.9+, and the new consensus support for light/fastsync.
